Repository SOPT-all/35-COLLABORATION-SERVER-LINKareer, pull requests merged in 2024-11, with the labels that each got.

#4 [chore] #3 .gitignore에 application.yml에 추가
  .gitignore
  src/main/resources/application.properties
Labels: enhancement, chore

#11 [hotfix] #5 ddl 오류 났던 부분 해결 - columnDefinition, @ColumnDefault 관련
  src/main/java/sopt35/linkareer/domain/chatting/infra/Chatting.java
Labels: hotfix

#18 [feat] #8 같은 관심사, 직무 인기 게시글 api 용 엔티티 생성
  src/main/java/sopt35/linkareer/domain/board/infra/Post.java
Labels: enhancement

#14 Feat#6 chatting api 구현 진행
  build.gradle
  src/main/java/sopt35/linkareer/annotation/.gitkeep
  src/main/java/sopt35/linkareer/annotation/Facade.java
  src/main/java/sopt35/linkareer/annotation/Generator.java
  src/main/java/sopt35/linkareer/api/controller/.gitkeep
  src/main/java/sopt35/linkareer/api/controller/ChattingController.java
  src/main/java/sopt35/linkareer/api/dto/response/ChattingHistoryApiResponse.java
  src/main/java/sopt35/linkareer/api/facade/.gitkeep
  src/main/java/sopt35/linkareer/api/facade/ChattingFacade.java
  src/main/java/sopt35/linkareer/domain/chatting/application/BlueCheckGenerator.java
  src/main/java/sopt35/linkareer/domain/chatting/application/ChatPartnerGenerator.java
  src/main/java/sopt35/linkareer/domain/chatting/application/ChatRoomInfoGenerator.java
  src/main/java/sopt35/linkareer/domain/chatting/application/NameGenerator.java
  src/main/java/sopt35/linkareer/domain/chatting/application/TagGenerator.java
  src/main/java/sopt35/linkareer/domain/chatting/application/dto/response/.gitkeep
  src/main/java/sopt35/linkareer/domain/chatting/application/dto/response/ChattingHistoryServiceResponse.java
  src/main/java/sopt35/linkareer/domain/chatting/application/service/.gitkeep
  src/main/java/sopt35/linkareer/domain/chatting/application/service/ChattingService.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/ChatPartnerVo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/ChatRoomVo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/ChatVo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/MyChatInfo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/PartnerVo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/ReplyVo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/TagVo.java
  src/main/java/sopt35/linkareer/domain/chatting/infra/ChattingEntity.java
  src/main/java/sopt35/linkareer/domain/chatting/infra/repository/.gitkeep
  src/main/java/sopt35/linkareer/domain/chatting/infra/repository/ChattingRepository.java
Labels: enhancement

#19 [feat] #10 추천 공고, 실시간 인기 공고 API 구현
  src/main/java/sopt35/linkareer/api/controller/OfficialController.java
  src/main/java/sopt35/linkareer/api/dto/response/ErrorCode.java
  src/main/java/sopt35/linkareer/api/dto/response/ErrorResponse.java
  src/main/java/sopt35/linkareer/api/dto/response/OfficialListResponse.java
  src/main/java/sopt35/linkareer/api/dto/response/OfficialResponse.java
  src/main/java/sopt35/linkareer/domain/official/application/dto/response/OfficialDto.java
  src/main/java/sopt35/linkareer/domain/official/application/service/OfficialService.java
  src/main/java/sopt35/linkareer/domain/official/infra/Category.java
  src/main/java/sopt35/linkareer/domain/official/infra/Official.java
  src/main/java/sopt35/linkareer/domain/official/infra/repository/OfficialRepository.java
  src/main/java/sopt35/linkareer/domain/official/validator/CategoryValidator.java
  src/main/java/sopt35/linkareer/global/exception/GlobalExceptionHandler.java
  src/main/java/sopt35/linkareer/global/exception/LinkareerException.java
Labels: enhancement

#23 [feat] 같은 관심사, 직무 인기 게시글 api 구현
  src/main/java/sopt35/linkareer/api/controller/PostController.java
  src/main/java/sopt35/linkareer/api/dto/response/PostsApiResponse.java
  src/main/java/sopt35/linkareer/api/facade/PostFacade.java
  src/main/java/sopt35/linkareer/domain/board/application/dto/request/.gitkeep
  src/main/java/sopt35/linkareer/domain/board/application/dto/response/.gitkeep
  src/main/java/sopt35/linkareer/domain/board/application/service/.gitkeep
  src/main/java/sopt35/linkareer/domain/board/infra/repository/.gitkeep
  src/main/java/sopt35/linkareer/domain/post/application/dto/request/.gitkeep
  src/main/java/sopt35/linkareer/domain/post/application/dto/response/PostsServiceResponse.java
  src/main/java/sopt35/linkareer/domain/post/application/service/PostService.java
  src/main/java/sopt35/linkareer/domain/post/application/vo/PostVo.java
  src/main/java/sopt35/linkareer/domain/post/infra/Post.java
  src/main/java/sopt35/linkareer/domain/post/infra/repository/PostRepository.java
  src/main/java/sopt35/linkareer/global/util/TimeCalculator.java
Labels: enhancement

#20 [feat] https 및 infra 설정
  Dockerfile
  src/main/java/sopt35/linkareer/domain/chatting/infra/Chatting.java
Labels: enhancement

#25 [feat] #24 게시글 api 카테고리 처리 구현
  src/main/java/sopt35/linkareer/api/controller/PostController.java
  src/main/java/sopt35/linkareer/api/facade/PostFacade.java
  src/main/java/sopt35/linkareer/domain/post/application/service/PostService.java
  src/main/java/sopt35/linkareer/domain/post/infra/category/Job.java
  src/main/java/sopt35/linkareer/domain/post/infra/category/Jobs.java
  src/main/java/sopt35/linkareer/domain/post/infra/category/PostCategory.java
  src/main/java/sopt35/linkareer/domain/post/infra/repository/PostRepository.java
  src/main/java/sopt35/linkareer/domain/post/validator/PostCategoryValidator.java
Labels: enhancement

#27 [refactor] #26 게시글 api 카테고리에 따른 분기 처리
  src/main/java/sopt35/linkareer/domain/post/application/service/PostService.java
  src/main/java/sopt35/linkareer/domain/post/infra/category/Job.java
  src/main/java/sopt35/linkareer/domain/post/infra/repository/PostRepository.java
Labels: enhancement

#29 [feat] #28 게시글 api 수정에 따른 변경
  src/main/java/sopt35/linkareer/domain/post/application/service/PostService.java
  src/main/java/sopt35/linkareer/domain/post/application/vo/PostVo.java
  src/main/java/sopt35/linkareer/global/config/.gitkeep
  src/main/java/sopt35/linkareer/global/exception/.gitkeep
  src/main/java/sopt35/linkareer/global/util/.gitkeep
  src/main/java/sopt35/linkareer/global/util/TimeCalculator.java
Labels: enhancement

#32 [feat] #31 게시글 api -> 가장 최신 게시물 3개를 내려주는 것으로 변경
  src/main/java/sopt35/linkareer/domain/post/application/service/PostService.java
  src/main/java/sopt35/linkareer/domain/post/infra/repository/PostRepository.java
Labels: enhancement

#33 [feat] replyMsg, message 바뀌어서 보내던 것 수정 진행 및 날짜 -> 시간으로 변경해서 보내주기
  src/main/java/sopt35/linkareer/domain/chatting/application/ChattingHistoryGenerator.java
  src/main/java/sopt35/linkareer/domain/chatting/application/dto/response/ChattingHistoryServiceResponse.java
  src/main/java/sopt35/linkareer/domain/chatting/application/service/ChattingService.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/ChatVo.java
  src/main/java/sopt35/linkareer/domain/chatting/application/vo/ChattingHistoryVo.java
Labels: enhancement, hotfix
